DROP DATABASE BDPANADERIA;
CREATE DATABASE BDPANADERIA;
USE BDPANADERIA;

CREATE TABLE IF NOT EXISTS PRODUCTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL UNIQUE,
PRECIO DOUBLE NOT NULL,
STOCK INT NOT NULL,
IMAGEN VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS INGREDIENTES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL UNIQUE,
PRECIO DOUBLE NOT NULL,
STOCK INT NOT NULL,
IMAGEN VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS NECESITA(
PR_ID INT,
ING_ID INT,
CANTIDAD INT NOT NULL,
FOREIGN KEY (PR_ID) REFERENCES PRODUCTOS(ID),
FOREIGN KEY (ING_ID) REFERENCES INGREDIENTES(ID),
PRIMARY KEY (PR_ID, ING_ID)
);

CREATE TABLE IF NOT EXISTS USUARIO(
ID INT PRIMARY KEY AUTO_INCREMENT,
USUARIO VARCHAR(50) NOT NULL UNIQUE,
CONTRASENA VARCHAR(50) NOT NULL,
ROL ENUM("CLIENTE","ALMACENERO","PANADERO","ADMINISTRADOR") NOT NULL,
CARTERA DOUBLE NOT NULL,
IMAGEN VARCHAR(50)
);

INSERT INTO USUARIO (USUARIO, CONTRASENA, ROL, CARTERA, IMAGEN) VALUES ("USUARIO1", "ABCD", "CLIENTE", 100.0, "a");
INSERT INTO USUARIO (USUARIO, CONTRASENA, ROL, CARTERA, IMAGEN) VALUES ("USUARIO2", "ABCD", "ALMACENERO", 50.0, "a");
INSERT INTO USUARIO (USUARIO, CONTRASENA, ROL, CARTERA, IMAGEN) VALUES ("USUARIO3", "ABCD", "PANADERO", 50.0, "a");
INSERT INTO USUARIO (USUARIO, CONTRASENA, ROL, CARTERA, IMAGEN) VALUES ("USUARIO4", "ABCD", "ADMINISTRADOR", 100.0, "a");


INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Pan Baguette", 1.10, 10, "baguette.png"); -- 1
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Pan Artesano", 2.50, 10, "artesano.png"); -- 2
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Croissant", 1.20, 10, "croissant.png"); -- 3
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Napolitana", 1.80, 10, "garrote.png"); -- 4
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Bizcocho", 3.50, 10, "bizcocho.png"); -- 5
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Trenza de Hojaldre", 12.00, 10, "trenza.png"); -- 6
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Pastas", 0.40, 50, "pastas.png"); -- 7

INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Harina", 0.70, 30, "harina.png"); -- 1
INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Levadura", 0.30, 30, "levadura.png"); -- 2
INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Azucar", 0.30, 30, "azucar.png"); -- 3
INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Chocolate", 0.80, 30, "chocolate.png"); -- 4
INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Hojaldre", 0.60, 30, "hojaldre.png"); -- 5
INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Leche", 1.00, 30, "leche.png"); -- 6
INSERT INTO INGREDIENTES (NOMBRE, PRECIO, STOCK, IMAGEN) VALUES ("Huevos", 0.20, 30, "huevos.png"); -- 7


INSERT INTO NECESITA VALUES ( 1, 1, 10);
INSERT INTO NECESITA VALUES ( 2, 1, 15);
INSERT INTO NECESITA VALUES ( 3, 5, 5);
INSERT INTO NECESITA VALUES ( 4, 5, 5);
INSERT INTO NECESITA VALUES ( 4, 4, 5);
INSERT INTO NECESITA VALUES ( 5, 1, 10);
INSERT INTO NECESITA VALUES ( 5, 2, 5);
INSERT INTO NECESITA VALUES ( 5, 3, 5);
INSERT INTO NECESITA VALUES ( 5, 6, 5);
INSERT INTO NECESITA VALUES ( 5, 7, 2);
INSERT INTO NECESITA VALUES ( 6, 5, 20);
INSERT INTO NECESITA VALUES ( 6, 3, 5);
INSERT INTO NECESITA VALUES ( 6, 6, 5);
INSERT INTO NECESITA VALUES ( 6, 4, 3);
INSERT INTO NECESITA VALUES ( 7, 1, 5);
INSERT INTO NECESITA VALUES ( 7, 2, 2);
INSERT INTO NECESITA VALUES ( 7, 3, 2);
INSERT INTO NECESITA VALUES ( 7, 6, 2);
INSERT INTO NECESITA VALUES ( 7, 7, 1);

UPDATE NECESITA SET CANTIDAD = 2 WHERE PR_ID = 1 AND ING_ID = 1;
SELECT CANTIDAD FROM NECESITA WHERE PR_ID = 1 AND ING_ID = 1;

select * from PRODUCTOS;

